// utils/classReportGenerator.js
const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");
const dayjs = require("dayjs");

/* ================= CONSTANTS ================= */
const BORDER_MARGIN = 25;
const CONTENT_START_Y = 200;   // ⬅ pushed DOWN to avoid header collision
const FOOTER_Y = 730;          // ⬅ safe footer (no auto page break)

/* ================= HELPERS ================= */
function ensureDir(p) {
  if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true });
}

function getGradeAndRemark(score) {
  if (score >= 70) return { grade: "A", remark: "Excellent" };
  if (score >= 60) return { grade: "B", remark: "Very Good" };
  if (score >= 50) return { grade: "C", remark: "Good" };
  if (score >= 40) return { grade: "D", remark: "Fair" };
  if (score >= 30) return { grade: "E", remark: "Weak" };
  return { grade: "F", remark: "Poor" };
}

function getRecommendation(avg) {
  if (avg >= 70) return "Excellent performance. Keep it up!";
  if (avg >= 60) return "Very good work. A little more effort needed.";
  if (avg >= 50) return "Good performance. Try to improve further.";
  if (avg >= 40) return "Fair effort. More study required.";
  return "Needs serious improvement.";
}

/* ================= MAIN ================= */
function generateClassReportPDF(meta, students, results, subjects, outPath, callback) {
  try {
    ensureDir(path.dirname(outPath));

    const doc = new PDFDocument({ margin: 40 });
    const stream = fs.createWriteStream(outPath);
    doc.pipe(stream);

    /* ========== HEADER ========== */
    function drawHeader() {
      doc.lineWidth(1).strokeColor("#888");
      doc.rect(
        BORDER_MARGIN,
        BORDER_MARGIN,
        doc.page.width - BORDER_MARGIN * 2,
        doc.page.height - BORDER_MARGIN * 2
      ).stroke();

      const logoPath = path.join(__dirname, "../public/logo.png");
      if (fs.existsSync(logoPath)) {
        try { doc.image(logoPath, doc.page.width / 2 - 20, 40, { width: 40 }); } catch {}
      }

      doc.font("Helvetica-Bold").fontSize(15);
      const name = meta.schoolName || "SCHOOL NAME";
      const boxW = doc.widthOfString(name) + 60;
      const boxX = (doc.page.width - boxW) / 2;
      const boxY = 90;

      doc.rect(boxX, boxY, boxW, 28).stroke();
      doc.text(name, 0, boxY + 7, { align: "center" });

      doc.font("Helvetica").fontSize(10);
      doc.text("Address: Behind Garko Motor park opp. Tasidi filling station", 0, boxY + 38, { align: "center" });
      doc.text("Motto: Success comes after tears", 0, boxY + 52, { align: "center" });
      doc.text("Phone: 08165789331, 08103992584, 08151015152", 0, boxY + 66, { align: "center" });

      doc.moveTo(60, boxY + 82).lineTo(540, boxY + 82).stroke();

      doc.y = CONTENT_START_Y;
    }

    /* ================= COVER ================= */
    drawHeader();
    doc.font("Helvetica-Bold").fontSize(14)
      .text("FULL CLASS REPORT", 0, CONTENT_START_Y, { align: "center" });

    let y = CONTENT_START_Y + 30;
    doc.font("Helvetica").fontSize(11);
    doc.text(`Class: ${meta.className}`, 60, y);
    doc.text(`Term: ${meta.term}`, 60, y + 18);
    doc.text(`Session: ${meta.session}`, 60, y + 36);
    doc.text(
      `Generated by ${meta.schoolName} — ${dayjs().format("YYYY-MM-DD HH:mm")}`,
      60,
      y + 60
    );

    doc.addPage();

    /* ================= STUDENT PAGES ================= */
    students.forEach((st, idx) => {
      drawHeader();

      doc.font("Helvetica-Bold").fontSize(13)
        .text("STUDENT REPORT SHEET", 0, CONTENT_START_Y, { align: "center" });

      let infoY = CONTENT_START_Y + 30;
      doc.font("Helvetica").fontSize(10);

      doc.text(`Name: ${st.name}`, 60, infoY);
      doc.text(`Class: ${meta.className}`, 60, infoY + 14);
      doc.text(`Admission No: ${st.id}`, 60, infoY + 28);

      doc.text(`Term: ${meta.term}`, 300, infoY);
      doc.text(`Session: ${meta.session}`, 300, infoY + 14);
      doc.text(`No. Students: ${meta.totalStudents}`, 300, infoY + 28);
      doc.text(`Position: ${st.position}`, 300, infoY + 42);

      const headers = ["Subject","Test1","Test2","Test3","Exam","Total","Grade","Remark"];
      const colX = [60,175,225,275,325,385,445,495];

      let tableY = infoY + 70;
      doc.font("Helvetica-Bold").fontSize(10);
      headers.forEach((h,i)=> doc.text(h, colX[i], tableY));
      doc.moveTo(60, tableY + 12).lineTo(540, tableY + 12).stroke();

      doc.font("Helvetica").fontSize(9);
      let rowY = tableY + 18;
      let total = 0, count = 0;

      subjects.forEach(sub => {
  const r = results.find(
    x => x.studentId === st.id && x.subject === sub.id
  ) || {};

  const t1 = +r.test1 || 0;
  const t2 = +r.test2 || 0;
  const t3 = +r.test3 || 0;
  const ex = +r.exam  || 0;

  const sum = t1 + t2 + t3 + ex;
  const { grade, remark } = getGradeAndRemark(sum);

  total += sum;
  count++;

  const row = [
    sub.name,   // ✅ SUBJECT NAME ONLY
    t1,
    t2,
    t3,
    ex,
    sum,
    grade,
    remark
  ];

  row.forEach((v, i) => doc.text(String(v), colX[i], rowY));
  rowY += 14;
});


      const avg = count ? (total / count).toFixed(2) : "0.00";

      rowY += 10;
      doc.font("Helvetica-Bold").fontSize(10);
      doc.text(`Subjects: ${count}`, 60, rowY);
      doc.text(`Total: ${total}`, 220, rowY);
      doc.text(`Average: ${avg}`, 380, rowY);

      rowY += 28;
      doc.text("Teacher's Recommendation:", 60, rowY);
      doc.font("Helvetica").text(getRecommendation(avg), 60, rowY + 14, { width: 380 });
    // Next Term
    doc.font("Helvetica-Bold").fontSize(10).text("Next Term Begins:",400,y);
    doc.font("Helvetica").fontSize(10).text("08/09/2026",400,y+14);
      let sigY = rowY + 90;
      doc.font("Helvetica-Bold");
      doc.text("Teacher's Signature:", 60, sigY);
      doc.text("Principal's Signature:", 350, sigY);

    // ===== TEACHER SIGNATURE (MATCH PER-STUDENT LOGIC) =====
let teacherSigPath = null;

if (st.classId) {
  const sigFile = `${st.classId}_signature.png`;

  const try1 = path.join(
    __dirname,
    "../public/uploads/teachers",
    sigFile
  );

  const try2 = path.join(
    __dirname,
    "../public/uploads",
    sigFile
  );

  if (fs.existsSync(try1)) teacherSigPath = try1;
  else if (fs.existsSync(try2)) teacherSigPath = try2;
}

// fallback from meta
if (!teacherSigPath && meta.teacherSignature) {
  teacherSigPath = path.join(
    __dirname,
    "..",
    meta.teacherSignature.replace(/^\//, "")
  );
}

// draw
if (teacherSigPath && fs.existsSync(teacherSigPath)) {
  doc.image(teacherSigPath, 60, sigY + 15, {
    width: 80,
    height: 40,
  });
} else {
  doc.text("____________________________", 60, sigY + 25);
}


      const principalSig = path.join(__dirname,"../public/uploads/principal_signature.png");
      if (fs.existsSync(principalSig)) doc.image(principalSig,350,sigY+15,{width:80,height:40});

      doc.font("Helvetica").fontSize(8)
        .text(`Generated by ${meta.schoolName} — ${dayjs().format("YYYY-MM-DD")}`, 60, FOOTER_Y);

      if (idx < students.length - 1) doc.addPage();
    });

   /* ================= SUMMARY ================= */
doc.addPage();
drawHeader();

doc.font("Helvetica-Bold").fontSize(13)
  .text("CLASS SUMMARY", 0, CONTENT_START_Y, { align: "center" });

let sy = CONTENT_START_Y + 30;
doc.font("Helvetica").fontSize(10);
doc.text(`Class: ${meta.className}`, 60, sy);
doc.text(`Term: ${meta.term}`, 60, sy + 14);
doc.text(`Session: ${meta.session}`, 60, sy + 28);
doc.text(`Total Students: ${meta.totalStudents}`, 60, sy + 42);

/* ---------- TABLE SETUP ---------- */
const col = { n:60, i:220, t:320, a:390, p:460 };
let tableSY = sy + 60;
const ROW_H = 14;
const PAGE_BOTTOM = FOOTER_Y - 80;

const drawTableHeader = (y) => {
  doc.font("Helvetica-Bold");
  doc.text("NAME", col.n, y);
  doc.text("ID", col.i, y);
  doc.text("TOTAL", col.t, y);
  doc.text("AVERAGE", col.a, y);
  doc.text("POSITION", col.p, y);
  doc.moveTo(60, y + 12).lineTo(540, y + 12).stroke();
  doc.font("Helvetica");
};

drawTableHeader(tableSY);

let rowSY = tableSY + 18;

/* ---------- STUDENT ROWS (SAFE PAGINATION) ---------- */
students.forEach(s => {

  if (rowSY > PAGE_BOTTOM) {
    doc.addPage();
    drawHeader();
    drawTableHeader(CONTENT_START_Y);
    rowSY = CONTENT_START_Y + 18;
  }

  doc.text(s.name, col.n, rowSY);
  doc.text(s.id, col.i, rowSY);
  doc.text(String(s.totalScore), col.t, rowSY);
  doc.text(s.average.toFixed(2), col.a, rowSY);
  doc.text(s.position, col.p, rowSY);

  rowSY += ROW_H;
});

/* ---------- SIGNATURES (GUARANTEED SPACE) ---------- */
if (rowSY + 100 > PAGE_BOTTOM) {
  doc.addPage();
  drawHeader();
  rowSY = CONTENT_START_Y;
}

let sigSY = rowSY + 30;

doc.font("Helvetica-Bold");
doc.text("Teacher's Signature:", 60, sigSY);
doc.text("Principal's Signature:", 350, sigSY);

/* ===== TEACHER SIGNATURE (SUMMARY PAGE – FIXED & SAFE) ===== */
let teacherSigPath = null;
const classId = meta.classId || meta.className;

if (classId) {
  const sigFile = `${classId}_signature.png`;

  const try1 = path.join(__dirname, "../public/uploads/teachers", sigFile);
  const try2 = path.join(__dirname, "../public/uploads", sigFile);

  if (fs.existsSync(try1)) teacherSigPath = try1;
  else if (fs.existsSync(try2)) teacherSigPath = try2;
}

if (!teacherSigPath && meta.teacherSignature) {
  teacherSigPath = path.join(
    __dirname,
    "..",
    meta.teacherSignature.replace(/^\//, "")
  );
}

if (teacherSigPath && fs.existsSync(teacherSigPath)) {
  doc.image(teacherSigPath, 60, sigSY + 15, { width: 80, height: 40 });
} else {
  doc.text("____________________________", 60, sigSY + 25);
}

/* ----- PRINCIPAL SIGNATURE ----- */
const pSig = path.join(__dirname, "../public/uploads/principal_signature.png");
if (fs.existsSync(pSig)) {
  doc.image(pSig, 350, sigSY + 15, { width: 80, height: 40 });
}

/* ---------- FOOTER ---------- */
doc.font("Helvetica").fontSize(8)
  .text(
    `Generated by ${meta.schoolName} — ${dayjs().format("YYYY-MM-DD HH:mm")}`,
    60,
    FOOTER_Y
  );

doc.end();
stream.on("finish", () => callback && callback(null, outPath));
stream.on("error", e => callback && callback(e));

  } catch (e) {
    callback && callback(e);
  }
}

module.exports = { generateClassReportPDF };
